### ISSUE TITLE
FastSpeech pretrain model

### ISSUE THREAD

**Issue by xcmyz** [PaddlePaddle/Parakeet#1]
Good job! Can you provide pretrained fastspeech model or some samples?

**Comment by 752377941** [comment]
I try to train it ,but it cant't work as intended

**Comment by 752377941** [comment]
Could you give me some suggestions?

![批注 2020-04-07 145803](https://user-images.githubusercontent.com/32575098/78639543-bb622400-78e0-11ea-9dc8-5f68fcdf0b8c.png)

**Comment by kuke** [comment]
Thanks! We have the plan, but we have to do more verification before that. Both the pre-trained model and audio samples will come soon. Please keep attention.

**Comment by qo4on** [comment]
One month has passed. Any update on this?
