### ISSUE TITLE
Comparison between this and Picovoice Cheetah/Leopard

### ISSUE THREAD

**Issue by BradKML** [PaddlePaddle/Parakeet#117]
The current toolkit did not do a comparison with its competitors.
https://github.com/Picovoice/speech-to-text-benchmark#speech-to-text-engines

It would be good to at least make note in the documentation.

**Comment by iclementine** [comment]
Thanks for your advise.
Parakeet is mostly a library for TTS, which is usually evaluated on MOS and RTF. We will release audio samples add RTF benchmarking later on.
