### ISSUE TITLE
请问对参考音频有什么要求吗？

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/Parakeet#121]
比如长度，声道，频率等等。
项目projectdetail/2020850 中更换wav后在 4. 合成频谱 后会出错，无法生成结果。请问可能是什么原因

**Comment by iclementine** [comment]
需要的参考音频是单声道，采样率会被重采样到 16kHz.
如果第三步能正常返回结果。那么有可能的问题是在文本。我们目前写的文本处理是很简单的，还没有加入比较通用的文本处理功能，目前我们只能支持汉字和两个特殊符号 '%' 和 '$'， 分别表示短的和长的停顿。

```python
sentence = "语音的表现形式%在未来%将变得越来越重要$"
phones, tones = convert_sentence(sentence)
print(phones)
print(tones)

phones = np.array([voc_phones.lookup(item) for item in phones], dtype=np.int64)
tones = np.array([voc_tones.lookup(item) for item in tones], dtype=np.int64)
```

这部分能正常工作吗？
这部分我在 Aistudio 上增补一下说明。

**Comment by 60999** [comment]
这部分工作正常
之后加入代码
`phones = paddle.to_tensor(phones).unsqueeze(0)
tones = paddle.to_tensor(tones).unsqueeze(0)
utterance_embeds = paddle.unsqueeze(embed, 0)`
正常

`with paddle.no_grad():
    outputs = synthesizer.infer(phones, tones=tones, global_condition=utterance_embeds)
mel_input = paddle.transpose(outputs["mel_outputs_postnet"], [0, 2, 1])
fig = display.plot_alignment(outputs["alignments"][0].numpy().T)`
这部分出错

提示：
`35%|███▍      | 349/1000 [00:01<00:02, 308.83it/s]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2349: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(obj, collections.Iterator):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2366: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return list(data) if isinstance(data, collections.MappingView) else data
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/image.py:425: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  a_min = np.asscalar(a_min.astype(scaled_dtype))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/image.py:426: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  a_max = np.asscalar(a_max.astype(scaled_dtype))
content exhausted!`

声音文件在附件
[周星驰配音石班瑜.zip](https://github.com/PaddlePaddle/Parakeet/files/6677088/default.zip)

**Comment by iclementine** [comment]
content exhausted! 这个其实是正常的，我们设定了模型输出频谱帧数的上限为 1000，但是对于一些短的句子，可能只需要几百帧，内容说完了就可以结束了。

不过我试了一下，合成的语音并不像[尴尬]，可能还是说话人识别的模型不够好的原因。

**Comment by 60999** [comment]
提示正常，但是我这边最后出不来结果，请问能否分享一下项目文档。
上面提示 349/1000  没有达到1000帧就出错了，后面提示“content exhausted!”应该是错误的。

**Comment by iclementine** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/2020850
我把你提供的音频样本传到了项目的 ref_audio 文件夹里，然后改动第三节的部分，是正常运行的。

要不你贴一下其他的报错？content exhausted 是我们自己写的一个提示，说明语音不需要 1000 帧，attention 最高点到达编码器的最后一个位置并且持续 10 帧后，提前终止。

**Comment by 60999** [comment]
能否重新生成版本，现在公开的1.2版，ref_audio文件夹里也没有附件中的音频。

**Comment by iclementine** [comment]
好的，上次操作的时候好像音频没有被添加进去。1.3 版本加上了。

**Comment by 60999** [comment]
这个音色……完全不同，请问是什么原因呢，如何提高相似度。
[大家好$我是石班瑜$.zip](https://github.com/PaddlePaddle/Parakeet/files/6717268/default.zip)
压缩包中是语音，下面mp4链接可以直接下载该wav文件，无需改名即可播放。
https://user-images.githubusercontent.com/18821732/123449292-1a0edd00-d60e-11eb-98d1-be9443a3b9d9.mp4

**Comment by iclementine** [comment]
我觉得是模型的迁移没做好。这个声音更像 AISHELL-3 数据集的声音。而不是 reference 的声音。可能需要一个 reconstruction loss 才能解决这个问题。不过目前目前还没有实现这个功能，因为我们的 speaker encoder 需要的频谱和声学模型输出的频谱的配置不同，所以我们需要实现另外的 speaker encoder 来实现。

**Comment by 60999** [comment]
谢谢！期待更新版本
另外github上有多人声音提取的项目，是否可以用来参考。将单人的声音混杂后训练提取出单人的

**Comment by iclementine** [comment]
多说话人分离的项目，我们目前还没上排期。但是我们也在关注这类的研究
