### ISSUE TITLE
中文合成质量

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/Parakeet#122]
用tacotron2_aishell3合成了下中文语音，效果不太自然，请问该从哪些方面改进？另如何实现中英混合合成

**Comment by iclementine** [comment]
tacotron_aishell 3 是我们尝试的一个 voice cloning 的实验。实验下来的心得是 voice cloning 是一个相对复杂的流程，我们可能在 speaker encoding 上并未做得很好。另外用 AISHLL-3 多人数据集来训练 tacotron 也比单人数据集难一些，因为不同说话人的音色和韵律都有比较大的差异，单纯靠用于区分说话人的 speaker encoder 可能不足。

我们也在准备释出在标贝单人数据集上训练的结果，效果比 tacotron_aishell3 效果更好。

我想问问你是要做语音克隆呢？还是单人的语音合成呢？如果是单人，那么问题相对简单一些，直接用 tacotron 2 其实也能达到不错的效果。我们目前在做的工作主要是用 parallel 的模型来达到好的音质。

如果是要做 voice cloning，可能添加一个 speaker encoding 的 reconstruction loss 会好些。亦即声学模型输入包含一个 speaker encoding, 然后对其生成的频谱再提取一次 speaker encoding, 这两个进行对比做 reconstruction loss.

中英混合这个事情我们正在准备，如果没有中英混合的语料的话.

1. 一个可能的策略是分别训练两个模型，使用 code switching 切换，把合成的频谱拼起来，然后再用声码器合成。
2. 另一个做法是我们更倾向的做法是，中英文的模型共享参数，比如说除了 embedding 都是共享的，或者除了 encoder 都是共享的。然后中英文数据分别训练。先用一种语言A训练，然后切换语言B的数据集训练，固定共享部分的参数，只训练语言B专属的那部分参数。训练到一定程度，固定语言B专属的那部分参数，更新共享的参数，然后再切换A语言训练，如此往复。

可以参考 https://arxiv.org/abs/2008.00768 的做法。

**Comment by FrankWhh** [comment]
感谢深夜回复，是在国内吗...
我刚接触语音合成，领导的意思是做个语音克隆；对您的回答没太看懂，我再看看文献资料，谢谢

**Comment by iclementine** [comment]
我们当时是参考的这篇文章：
Transfer Learning from Speaker Veriﬁcation to Multispeaker Text-To-Speech Synthesis （https://arxiv.org/pdf/1806.04558.pdf）

是用一个声纹识别模型来做说话人特征提取的，模型训练也分几个阶段进行，好处是声纹识别模型可以不需要文本标注。

不过声学模型（文本 -> 声学特征(主要是频谱用)）的部分还是需要一个多说话人的带标注的数据集进行训练。
