### ISSUE TITLE
New version of praatio will break things

### ISSUE THREAD

**Issue by timmahrt** [PaddlePaddle/Parakeet#136]
Hi, I'm the maintainer of praatio, one of the dependencies used by this library.  Praatio 5.0 is not yet released but has some breaking changes in it.  The changes are not so heavy

If you want to avoid python 5.0 for now, you can modify `install_requires` in setup.py as follows:
from
`'praatio'`
to
`'praatio ~= 4.1'`

I'm sorry for the headache.  If you have any questions please let me know.  Thank you!

**Comment by iclementine** [comment]
Thank you for informing! I will check the updates.
