### ISSUE TITLE
ops

### ISSUE THREAD

**Issue by C4712** [PaddlePaddle/Parakeet#15]
ImportError: cannot import name 'ops' from 'paddle.fluid.core_avx' (/home/mao/anaconda3/envs/python37/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

**Comment by iclementine** [comment]
It seems the installation of paddlepaddle has somehow failed. May be you can first try reinstalling paddlepaddle.

If the installation is done, then there should be a `site-packages/paddle/fluid/core_avx.so`. You can check it out.
