### ISSUE TITLE
中文中有少许英文字母 和单词该怎么处理

### ISSUE THREAD

**Issue by kunyao2015** [PaddlePaddle/Parakeet#175]
看了关于aishell3的相关example来作为tts入门,学到了许多, 想了解下,如题中文中夹杂一些单词和字母, 该怎么形成如同simple.lexicon 以及包含拼音信息的 .lab文件呢 ,谢谢了

**Comment by yt605155624** [comment]
你好，aishell3 是一个开源的中文多说话人数据，数据集中提供了拼音标签，我们直接把拼音标签拿出来再使用 simple.lexicon 映射为音素序列，没有专门处理原始文本是英文的情况，simple.lexicon 的生成方式可以参考 https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/use_mfa/local/generate_lexicon.py 我们根据中文拼音的拼读规则生成了一套和 baker 数据集匹配的音素序列，包含拼音的 lab 文件的生成方式可以参考 https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/use_mfa/local/reorganize_aishell3.py ，生成 lab 文件之后您就可以训练自己的 MFA 模型了。此外，如果您想要处理英文的情况，一般英文使用的是 CMUDict 这个音素标准，您可以把 cmudict 和 simple.lexicon 拼接在一起形成一个中英文双语的 单词/拼音 -> 音素字典， parakeet 的 transformer_tts 的例子是英文的，您可以参考下怎么使用 cmudict

**Comment by kunyao2015** [comment]
感谢指导, 期待Parakeet有更多更好的分享
