### ISSUE TITLE
这个仓库缺少韵律预测前端模块，导致TTS韵律节奏很差

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Parakeet#188]
你好，这个仓库缺少韵律预测前端模块，导致TTS韵律节奏很差。有TTS韵律预测的模型如bert支持吗

**Comment by yt605155624** [comment]
目前是没有的，请问您实验的是哪个声学模型？

**Comment by youngstu** [comment]
Fastspeech2声学模型

**Comment by youngstu** [comment]
https://paddleparakeet.readthedocs.io/en/latest/demo.html

文档里面提供的音频示例听着是有韵律的，能介绍一下吗？谢谢。

![Screenshot from 2021-09-29 19-24-47](https://user-images.githubusercontent.com/26452514/135259405-d1cdc4e2-7313-43e0-83a9-ed7f8f4e683b.png)

**Comment by yt605155624** [comment]
demo 中提供的音频确实就是用我们提供的预训练模型合成出来的，https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/fastspeech2/baker/synthesize_e2e.py 文本是 https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/fastspeech2/sentences.txt 你可以自己合成试试

**Comment by youngstu** [comment]
好的，能解释一下with/without text frontend 都包括那些处理呢？

**Comment by yt605155624** [comment]
https://paddleparakeet.readthedocs.io/en/latest/cn_text_frontend.html

**Comment by youngstu** [comment]
看来主要是变调处理，变调处理会影响这么大吗？看到TensorflowTTS Fastspeech2 也没有对变调处理，效果也还好。

**Comment by yt605155624** [comment]
TensorFlowTTS 我没跑过，espnet里面的做法是训练的时候再和预测的时候都用的是pypinyin（没有变调），这导致他们的模型其实学到了错误的音调比如bu4，在发音的时候有二声和四声的情况，但是可能pypinyin只标了四声，导致他们的模型在看到 bu4的时候有时候发出四声有时候发出二声，这种一对多的情况是错误的（关于这个例子你可以多听几条他们的输出，会有模棱两可的情况）
我们的模型在训练的时候是用的baker自己的标注数据，其中大部分是包含正确的变调的，所以为了解决训练和预测前端的mismatch，需要添加变调模块

**Comment by youngstu** [comment]
了解。还有一个Bilingual &code-switch问题，我们可以加如流好友吗？交流一下

**Comment by yt605155624** [comment]
yuantian01
