### ISSUE TITLE
I try to train the fastspeech model, but it doesn't work as intended

### ISSUE THREAD

**Issue by Victor-Chow** [PaddlePaddle/Parakeet#2]
I got some noise frome synthesis

**Comment by lfchener** [comment]
Thanks for attention.
We will update the code in near future to solve this problem. Please keep following us.

**Comment by Victor-Chow** [comment]
> Thanks for attention.
> We will update the code in near future to solve this problem. Please keep following us.

I found that duration can align when I adjust lr value to 0.0005, but it still is noise
![fastspeech_174000_mel_output_postnet](https://user-images.githubusercontent.com/32575098/79211781-43b06e00-7e79-11ea-96a7-1c819822500c.png)

**Comment by lfchener** [comment]
This is because the data preprocessing method is not suitable for the Fastspeech, please waiting for the code upgrade that has solved this problem in near future.
Thanks for your attention.
