### ISSUE TITLE
Chinese frontend prosody struct predict

### ISSUE THREAD

**Issue by lightwithshadow** [PaddlePaddle/Parakeet#204]

**Comment by yt605155624** [comment]
You can use the prosody data in csmsc(#1 #2 #3 #4) and train a simple seq2seq language model(for example BERT)
ps. Our repo is moving to https://github.com/PaddlePaddle/DeepSpeech now, You can issue there

**Comment by lightwithshadow** [comment]
Thank you for your reply, is it the data of Biaobei 1W sentences?  Does BERT delay too long？

**Comment by yt605155624** [comment]
YES, It's the data of Biaobei 1W sentences, BERT will be too large for only a prosody task, you can chose a small language model, or You can use BERT to resolve a multi-task frontend, for example, prosody predict + polyphone predict + tone sandhi, etc
