### ISSUE TITLE
How to use JUST dataset for fastspeech?

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Parakeet#24]
想用JUST 数据集训练一下日语数据库，对数据集替换上有一点疑问，怎么替换呢？

**Comment by lfchener** [comment]
你可以修改 data.py 中的相关部分来适配 JUST 数据集：
https://github.com/PaddlePaddle/Parakeet/blob/develop/examples/fastspeech/data.py#L69
dataset 部分的使用可详见 README：
https://github.com/PaddlePaddle/Parakeet/tree/develop/parakeet/datasets
