### ISSUE TITLE
when i run sys synthesis.py of waveflow,get a NotFoundError

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/Parakeet#25]
File "D:\SoftWare\Anaconda\envs\Parakeet\lib\site-packages\paddle\fluid\layers\nn.py", line 7372, in reshape
    out, _ = core.ops.reshape2(x, 'shape', shape)
paddle.fluid.core_avx.EnforceNotMet: 

Error Message Summary:
----------------------
NotFoundError: Operator reshape2 does not have kernel for data_type[::paddle::platform::float16]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] at (D:\1.8.2\paddle\paddle\fluid\imperative\prepared_operator.cc:118)

**Comment by kuke** [comment]
This should result form a lower version PaddlePaddle than the requirement. Did you install PaddlePaddle above 1.8.2?

**Comment by Ficery1** [comment]
Thanks.It is a version error.
My version is gpu-1.8.2,but set use_gpu=False whern i run .
