### ISSUE TITLE
怎么在waveflow的模型上使用多个CPU进行训练？

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/Parakeet#26]
OS: Linux
昨天热心人回应设置
os.environ["CPU_NUM"]=8
并不起作用，
根据监控8核CPU还是1个100%占用，其他均无负荷。
谢谢。

**Comment by kuke** [comment]
目前Paddle动态图对多 CPU 的训练支持还不太行，下一个版本应该会有所改善
