### ISSUE TITLE
不能修改下lookup_table的最大值么？id 只能到1024？

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Parakeet#30]
Error: /paddle/paddle/fluid/operators/lookup_table_v2_op.cu:43 Assertion `id < N` failed. Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got 1062. Please check input value.

这种错误应该修改什么参数？

**Comment by iclementine** [comment]
出现这个问题是你的 id 数值超过词表大小了。可以先检查一下
