### ISSUE TITLE
Bug in training

### ISSUE THREAD

**Issue by YangHan-Morningstar** [PaddlePaddle/Parakeet#32]
hi, when I following the readme to train the transformer, I got an error that 
Traceback (most recent call last):
  File "train_transformer.py", line 26, in <module>
    from parakeet.models.transformer_tts.utils import cross_entropy
ModuleNotFoundError: No module named 'parakeet'
But I can't find the models file in the file, could you tell me how to solve it? Thanks a lot!

**Comment by iclementine** [comment]
You can first install parakeet by `pip install -e .`
