### ISSUE TITLE
deepvoice合成语音耗时长

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/Parakeet#34]
您好。
deepvoice合成一条20个汉字的语音要一分钟；
而且合成的语音wav都是20-30秒，语音主要在wav的开头、中间和结尾处，其他地方多是空白。
这种情形，应该怎么优化呐？
谢谢。

**Comment by iclementine** [comment]
请问你是用自定义的中文语音数据集进行了训练吗？
那么，可能需要注意

1. 模型能处理的字符集是否正确；
2. 模型是否充分训练了。

另外，频谱生成终止的条件是形成单调对角 attention 的层的 attention 关注点达到最后一个字符，或者达到最大长度限制。如果字符集都没有问题，那么可能模型训练出了问题，频谱的生成未能正确地停下来。
