### ISSUE TITLE
Deepvoice3 的最新预训练模型在哪下载呢？

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Parakeet#36]
看到deepvoice3 的最新版本结合了waveflow想试验下合成效果：
首先更新了本地库，然后按照介绍尝试着运行了如下合成命令：
python synthesize.py --config configs/ljspeech.yaml --input sentences.txt --output sy_outputs/ --checkpoint pre_model/step-1560000 --monotonic_layers "5,6" --vocoder waveflow

报错：RuntimeError: Parameter not found, Can't not find [ char_embedding.weight ] in stat_dictuse_structured_name is set to [True]

这里的预训练模型是之前下载的，现在我看Parakeet下已经没有deepvocie3预训练模型下载了。
这块的报错是跟什么有关呢？

**Comment by iclementine** [comment]
deep voice 3 模型做了一次较大的变动，所以之前的 checkpoint 已经不兼容。新的 checkpoint 没有放出是因为我们在公开的 ljspeech 上暂时没有调到很好的效果。但是在内部数据集上的 checkpoint 因为数据集的授权原因不能放出。
