### ISSUE TITLE
RuntimeError: Parameter not found

### ISSUE THREAD

**Issue by ymzlygw** [PaddlePaddle/Parakeet#38]
当我使用deepvoice3 + waveflow 合成语音的时候出现下面这个错误：

RuntimeError: Parameter not found, Can't not find [ char_embedding.weight ] in stat_dictuse_structured_name is set to [True]

命令行使用的是说明给的代码：python synthesize.py \
> --config configs/ljspeech.yaml \
> --input sentences.txt \
> --output outputs// \
> --checkpoint pre_model/step-1560000 \        
> --monotonic_layers "5,6" \
> --vocoder waveflow

为什么会报错呢？

**Comment by iclementine** [comment]
请问是使用之前下载的 checkpoint 吗？ 因为一次较大的升级， 我们之前发布的 checkpoint 不再兼容了。所以目前的推荐自行训练。
