### ISSUE TITLE
运行了一下train脚本，重新训练transformer_tts，结果合成语音时报错

### ISSUE THREAD

**Issue by GuoRab** [PaddlePaddle/Parakeet#39]
请问一下这是为什么呢，运行了一下train脚本，重新训练transformer_tts，结果合成语音时报错：
![合成报错](https://user-images.githubusercontent.com/73027386/96339622-7c4f2f80-10c8-11eb-9437-30f909ab4f02.png)

**Comment by lfchener** [comment]
![image](https://user-images.githubusercontent.com/6771821/97254573-a1bb0680-1849-11eb-82c2-3d7d30f404e4.png)

可以先 check 一下变量 spec 的shape，猜测可能是你的训练步数太少，所以合成结果有问题导致的。

**Comment by GuoRab** [comment]
> ![image](https://user-images.githubusercontent.com/6771821/97254573-a1bb0680-1849-11eb-82c2-3d7d30f404e4.png)
> 
> 可以先 check 一下变量 spec 的shape，猜测可能是你的训练步数太少，所以合成结果有问题导致的。
我是没有对代码做任何改动，直接sh train_transformer.py的，训练到12万之后，合成时还是同样的报错。
后，检查发现是stop_loss 训练的不好（每次都直接停掉了），后在合成时删除了关于stop_loss的判断，可以合成出语音了，但是合成的语音只有噪声（或者只有一两个杂音），请问这是怎么回事？（在百度的aistudio里面训练的）
![合成备注两行](https://user-images.githubusercontent.com/73027386/97582838-2ddb5280-1a31-11eb-9641-0126954f723d.png)

**Comment by GuoRab** [comment]
> ![image](https://user-images.githubusercontent.com/6771821/97254573-a1bb0680-1849-11eb-82c2-3d7d30f404e4.png)
> 
> 可以先 check 一下变量 spec 的shape，猜测可能是你的训练步数太少，所以合成结果有问题导致的。



> ![image](https://user-images.githubusercontent.com/6771821/97254573-a1bb0680-1849-11eb-82c2-3d7d30f404e4.png)
> 
> 可以先 check 一下变量 spec 的shape，猜测可能是你的训练步数太少，所以合成结果有问题导致的。

我是没有对代码做任何改动，直接在百度的aistudio里面 4卡脚本（每个卡batch_size=16）训练的，训练到12万之后，合成时还是同样的报错。检查发现是stop_loss 训练的不好（每次都直接停掉了），后在合成时删除了关于stop_loss的判断，可以合成出语音了，但是合成的语音还是胡言乱语，请问这是怎么回事？
