### ISSUE TITLE
why fix the embedding size in transformer_tts

### ISSUE THREAD

**Issue by zzz2010** [PaddlePaddle/Parakeet#42]
Hi,
 I found the  transformer_tts code with fix embedding size as 1024, which is not enough if we want to apply to pinyin. Any thought?

https://github.com/PaddlePaddle/Parakeet/blob/1db01ccc90d11ec7c75d707db4932f9d4c98fcf6/parakeet/models/transformer_tts/encoder.py#L42

```
        self.pos_inp = get_sinusoid_encoding_table(
            1024, self.num_hidden, padding_idx=0)
        self.pos_emb = dg.Embedding(
            size=[1024, num_hidden],
            param_attr=fluid.ParamAttr(
                initializer=fluid.initializer.NumpyArrayInitializer(
                    self.pos_inp),
                trainable=False))
```

**Comment by iclementine** [comment]
Actually， we always use a fixed positional encoding. Positional encoding (the sin-cos positional encoding is used a inductive bias to lead the attention weight to concentrate on the diagonal line, which is the nature of synchronization of text and voice.
