### ISSUE TITLE
Multi-Gpu support for deepvoice3

### ISSUE THREAD

**Issue by aayushkubb** [PaddlePaddle/Parakeet#7]
How can I enable multi-gpu training for deepvoice3?

**Comment by iclementine** [comment]
Techically we can enable multi-gpu training for deep voice 3 by wrapping the model with `DataParallel` and make other minor adaptations, but the sampler used when training deep voice 3 now does not support multi-gpu training. We are now working on adding parallel training support for it.

And we haved made some optimizations to accelerate training for deep voice 3. There would be an update soon.

**Comment by aayushkubb** [comment]
Okay thanks
