### ISSUE TITLE
中文数据集上的语音合成

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/Parakeet#79]
能不能出一个中文数据集语音合成的文档或者注意事项，期待中...

**Comment by iclementine** [comment]
中文语音合成的模型我们近期计划用标贝数据集来一个 Experiment

**Comment by Godlikemandyy** [comment]
耶~~~

**Comment by moondiy** [comment]
> 中文语音合成的模型我们近期计划用标贝数据集来一个 Experime等待ing

**Comment by yt605155624** [comment]
> > 中文语音合成的模型我们近期计划用标贝数据集来一个 Experime等待ing

你好，现在我们为中文数据集 biaobei 提供了声学模型 speedyspeech 和 fastspeech2 ，声码器提供了 parallel wavgan 的 example, 请可以到主页 readme 找到相应链接
